sunriselayer/sunrise

- docs/static/openapi.yml
- x/liquidstaking/module/autocli.go
Fix Invalid Msg
```
LiquidStake => MintDerivative
LiquidUnstake => BurnDerivative
```
> fix: sunrised

- .gitignore
- .vscode/extensions.json
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- app/abci_process_proposal.go
- go.mod
- scripts/setup/init.sh
- scripts/setup/variables.sh
- Create build ＆launch script for VScode
- Delete Data hash check, because sunrise-core's `RequestProcessProposal` does not include DataHash calculation results.
Previous implementations compared the TxHash in the request and calculated DataHash, so they are mismatch.
> feat: sunrised debug

- app/abci_process_proposal.go
- go.mod
- go.sum
- go.work.sum
- Add txs length 0 handling
https://github.com/SunriseLayer/sunrise-app/pull/11/commits/052ebe58c6c5ef7f7065a92590fdccdbcf4b11d6
- Update sunrise-core latest version
> feat: first txs handing & core update

- go.mod
- go.work.sum
fix sunrise-core RPC 
https://github.com/SunriseLayer/sunrise-core/pull/10
> fix: core RPC

- x/blobstream/module/module.go
Fix to add blobstream to EndBlocker handler
> fix: register endblock blobstream

- test/util/testnode/rpc_client.go
> fix: stop func

- app/defaultoverrides/bank.go
> feat: VRISE to vRISE

- x/swap/module/ibc_middleware.go
- x/swap/types/ibc.go
> feat: swap ibc

- docs/static/openapi.yml
Include gov/v1 into openapi.yml for frontend support
`ignite generate openapi --clear-cache`
`sed -i '7,19474d' docs/static/openapi.yml`
`sed -i '3132,51464d' docs/static/openapi.yml`
> chore: OpenAPI included gov v1

- x/liquiditypool/keeper/msg_server_position.go
> chore: error detail (create-position)

- x/swap/types/route.go
close #82
I fix problem with Swap Series not working.
> fix: Swap Route_Series

- x/liquiditypool/keeper/incentives_test.go
- x/liquiditypool/keeper/msg_server_claim_rewards_test.go
- x/liquiditypool/keeper/msg_server_pool_test.go
- x/liquiditypool/keeper/msg_server_position_test.go
- x/liquiditypool/keeper/pool.go
- x/liquiditypool/keeper/position.go
- x/liquiditypool/keeper/query_pool_test.go
- x/liquiditypool/keeper/query_position_test.go
- x/liquiditypool/keeper/swap_test.go
This reverts commit 0412fa10b4ecf15e68c476f668a56eb5f5e065c3.
> fix: Revert "pool and position counting from 1 and fix unit tests"

- x/swap/keeper/ibc.go
- x/swap/module/ibc_middleware.go
- x/swap/types/ibc_test.go
> fix: IBC Transfer timeout

- README.md
- scripts/setup/single-node.sh
> fix: readme & script

- pkg/inclusion/blob_share_commitment_rules_test.go
- pkg/wrapper/README.md
> fix: typos

- docs/static/openapi.yml
- test/e2e/readme.md
- test/util/common.go
Hello
While looking through your docs I found and fixed several spelling issues.
Br, Elias.
> Docs fix spelling issues

- api/sunrise/liquidityincentive/query.pulsar.go
- api/sunrise/liquidityincentive/query_grpc.pb.go
- docs/static/openapi.yml
- proto/sunrise/liquidityincentive/query.proto
- x/da/types/query.pb.gw.go
- x/liquidityincentive/keeper/query_vote.go
- x/liquidityincentive/module/autocli.go
- x/liquidityincentive/types/query.pb.go
- x/liquidityincentive/types/query.pb.gw.go
- Add GaugeVote & GaugeVotes query
> feat: Gauge Vote Query

- app/app.go
- app/upgrades/v0.2.1-test/constants.go
- app/upgrades/v0.2.1-test/upgrades.go
- go.mod
- go.work.sum
close #119
Solve the issue #119 with an empty Upgrade.
> fix: consensus-error after upgrade

- app/app.go
- app/upgrades/README.md
- app/upgrades/v0.2.1-test/constants.go
- app/upgrades/v0.2.1-test/upgrades.go
- go.mod
- go.work.sum
- x/fee/README.md
- x/liquidityincentive/README.md
- x/liquiditypool/README.md
- x/swap/README.md
- x/tokenconverter/README.md
> feat: update document

- app/upgrades/v0.2.1-test/send_coin.go
- app/upgrades/v0.2.1-test/upgrades.go
> feat: v0.2.1 new-validators

- app/ibc.go
> fix: ica host keeper

- app/app.go
- app/upgrades/v0.2.3-test/constants.go
- app/upgrades/v0.2.3-test/send_coin.go
- app/upgrades/v0.2.3-test/upgrades.go
Upgrade v0.2.3 
Send token to validator 01node in the public testnet.
> feat: upgrade v0.2.3

- go.work.sum
- x/da/erasurecoding/go.mod
> fix: go.mod module name

- app/app.go
- app/lanes.go
- app/upgrades/v0.2.4-test/constants.go
- app/upgrades/v0.2.4-test/upgrades.go
> feat: max txs

- app/ante/ante.go
> chore: comment

- app/app.go
- app/upgrades/v0.2.5-test/constants.go
- app/upgrades/v0.2.5-test/upgrades.go
- x/liquiditypool/keeper/msg_server_position.go
#140 fix for Testnet binary v0.2.x
> #140 for testnet

- app/app.go
- app/upgrades/v0.2.6-test/constants.go
- app/upgrades/v0.2.6-test/upgrades.go
Fix problem with AnteHadler not being set properly.
This fix may correct a problem that some users are experiencing that prevents Tx from processing properly.
> feat: v0.2.x block sdk fixes

- x/liquiditypool/keeper/store_position.go
> order of remove

- x/tokenconverter/module/autocli.go
Fixed problem with chain not starting
> fix: auto cli

- app/app.go
> revert: lockup depinject

- x/da/keeper/keeper_slash.go
- x/da/keeper/keeper_threshold.go
fix for F-2025-8618 | Issues with Threshold Calculation Mechanisms
> fix: Threshold use Ceil()

- proto/sunrise/lockup/v1/query.proto
- proto/sunrise/shareclass/v1/query.proto
- x/fee/keeper/keeper_burn.go
- x/shareclass/keeper/msg_server_non_voting_delegate.go
- x/shareclass/keeper/msg_server_non_voting_undelegate.go
added amount validation also for shareclass msgs
> amount-validation

- app/app.go
- app/app_config.go
- app/custom/bank.go
- app/custom/custom.go
- app/custom/fee.go
- app/custom/gov.go
- app/custom/mint.go
- app/custom/protocolpool.go
- app/custom/staking.go
- cmd/sunrised/cmd/root.go
Change custom module's DefaultGenesis() https://github.com/exoralayer/exora/pull/3
Fix `x/protocolpool` ValidateGenesis()
https://github.com/cosmos/cosmos-sdk/issues/24592
> fix: v0.53 genesis

- app/app.go
- app/app_config.go
- app/gov/gov.go
- x/liquidityincentive/keeper/keeper_tally.go
- fix quorum adjustment for gov custom tally
- remove the voting power of shareclass module delegation in liquidityincentive tally
> V0.53 tally

- proto/sunrise/liquiditypool/v1/pool.proto
- proto/sunrise/liquiditypool/v1/tx.proto
- x/liquiditypool/README.md
- x/liquiditypool/keeper/keeper_incentives_test.go
- x/liquiditypool/keeper/keeper_swap_test.go
- x/liquiditypool/keeper/keeper_tick_test.go
- x/liquiditypool/keeper/msg_server_claim_rewards_test.go
- x/liquiditypool/keeper/msg_server_create_pool.go
- x/liquiditypool/keeper/msg_server_pool_test.go
- x/liquiditypool/keeper/msg_server_position_test.go
- x/liquiditypool/types/pool.pb.go
- x/liquiditypool/types/tx.pb.go
> fix: base offset validation

- x/liquiditypool/keeper/keeper_incentives.go
Fix
```
panic: invalid zero decimal
goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/types.DecCoins.QuoDecTruncate({0xc0034e15f0?, 0x1?, 0x1?}, {0xc0015a89e0?})
/root/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.53.0/types/dec_coin.go:433 +0x172
github.com/sunriselayer/sunrise/x/liquiditypool/keeper.Keeper.AllocateIncentive({{0x52d1830, 0xc001418530}, {0x522a4e0, 0xc0015a89e0}, {0x528c980, 0xc0007c7490}, {0xc00170e660, 0x2e}, {0x5251500, 0xc0013ab7a0}, ...}, ...)
/root/sunrise/x/liquiditypool/keeper/keeper_incentives.go:22 +0x265
github.com/sunriselayer/sunrise/x/liquidityincentive/keeper.Keeper.BeginBlocker({{0x52d1830, 0xc001418530}, {0x522a4e0, 0xc00166da10}, {0x528c980, 0xc0007c7490}, {0xc00170e660, 0x2e}, {0x5251500, 0xc0013ab7a0}, ...}, ...) …
```
> fix: zero divide

- app/app.go
- app/app_config.go
- app/ibc.go
Add app.go & app_config.go settings for #254
Reference
- cosmos/ibc-go/docs/docs/03-light-clients/04-wasm/03-integration.md
- cosmos/ibc-go/modules/light-clients/08-wasm/testing/simapp/app.go
> feat: App for IBC Integration

- x/shareclass/keeper/keeper_delegate.go
> fix: undelegate amount in shareclass

- x/fee/ante/denom.go
> feat: allow empty fee for estimate gas

- x/swap/types/codec.go
> fix: register tx extension option

- .gitignore
- CLAUDE.md
- app/gov/gov.go
- x/da/keeper/keeper_threshold.go
- x/liquiditypool/keeper/keeper_tick.go
- fix Zero divide
`app/gov/gov.go` (`ProvideCalculateVoteResultsAndVotingPowerFn`)
`x/da/keeper/keeper_threshold.go` (`GetZkpThreshold`)
- add negative liquidity validation
`x/liquiditypool/keeper/keeper_tick.go` (`UpsertTick`)
> fix: minor bugs

- README.md
> docs: the discord link didn't work.

- app/upgrades/v1_1_0/upgrade.go
> fix: v1.1.0 patch for dawn-1

- .github/workflows/release.yml
- scripts/make-release-build.sh
> fix: sunrised version in docker

- app/custom/bank.go
- docs/static/openapi.yml
- x/shareclass/keeper/keeper_delegate.go
fix some minor issues in comments
> chore: fix some minor issues in comments
